name: build-main

on:
  push:
    branches: [develop, release-**]
  pull_request:
    branches: [develop, release-**]

jobs:
  call-build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Set POM version for dev branch
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: echo "pomversion=$(date +%Y-%m-%d)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set POM version for release branch
        if: ${{ startsWith(github.ref, 'refs/heads/release-') }}
        run: echo "pomversion=$(git describe --tags)" >> $GITHUB_ENV

      - uses: ./.github/workflows/build
        with:
          mvn_goal: deploy
          pom_version: ${{ env.pomversion }}
        env:
          MAVEN_USERNAME: ${{ secrets.PLATFORM_ARTIFACTORY_USER }}
          MAVEN_USERPWD: ${{ secrets.PLATFORM_ARTIFACTORY_PWD }}

      - name: setup-job-summary
        run: |
          echo "| version | ${{ env.pomversion }} |" > $GITHUB_STEP_SUMMARY

  call-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/build
        with:
          mvn_goal: test
